name: Snapshot

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [17]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        face-depth: 0
          
    - name: Validate Gradle wapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'gradle'

    - name: Make Gradle wrapper executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew

    - name: Build
      run: ./gradlew build --stacktrace --parallel

    - name: Capture build artifacts
      if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: build/libs/
